services:
  cargo_api:
    image: tugsuu002/cargomono:latest
    container_name: cargo_api
    ports:
      - 8082:8082
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    # networks:
      # - docker_cargo
