@localUrl = http://localhost:8082/api
@baseUrl = 
@accessToken=

### login
POST {{localUrl}}/auth/login
Content-Type: application/json

{
  "phone": "86662422",
  "password": "admin$123"
}

### list 
GET  {{localUrl}}/package

### check 
POST {{localUrl}}/package/check
Content-Type: application/json

{
  "trackCode": "йыбйыб"
}

### create
POST {{localUrl}}/package
Content-Type: application/json

{
  "height": 20,
  "width": 10,
  "weight": 8,
  "length": 50,
  "phone": "96268444",
  "registeredById": 1,
  "warehouseId": 1,
  "organizationId": 1,
  "trackCode": "YB35218856",
  "price": 5000,
  "notes": "test 1 бараа",
  "isExpress": false,
  "broken": false,
  "deliveryRequested": false
}



