@localUrl = http://localhost:8082/api
@baseUrl = 
@accessToken=


//orgMemberId заавал нэмж бичих хэрэгтэй!!!!!!!!!!!! pass:admin$123
### lgon

### login
POST {{localUrl}}/auth/login
Content-Type: application/json

{
  "phone": "86662422",
  "password": "admin$123"
}


GET {{localUrl}}/auth/user/1
Content-Type: application/json

### register
POST {{localUrl}}/auth/register
Content-Type: application/json

{
  "prefix":"976",
  "lastName":"Төгөлдөр",
  "firstName":"Сүмбэ",
  "phone": "86662422",
  "password": "admin$123"
}
### register
GET {{localUrl}}/auth/info
Content-Type: application/json
