@localUrl = http://localhost:8082/api
@baseUrl = 
@accessToken=

### login
POST {{localUrl}}/auth/login
Content-Type: application/json

{
  "phone": "86662422",
  "password": "admin$123"
}

### create
POST {{localUrl}}/warehouse
Content-Type: application/json

{
  "organizationId": 1,
  "name": "Darkhan Main Warehouse 1",
  "address": "Industrial District 3",
  "region": "Ulaanbaatar",
  "zipcode": "17042",
  "type": "NORMAL",
  "totalCapacity": 15000,
  "contactInfo": {
    "phone": "99112233",
    "email": "warehouse@company.mn"
  },
  "operatingHours": {
    "weekdays": "08:00-18:00",
    "weekends": "09:00-15:00"
  },
  "currency": {
    "kg": 3000,
    "m3": 400,
    "rate": 510
  }
}

### update
PUT {{localUrl}}/warehouse/1
Content-Type: application/json

{
  "organizationId": 1,
  "name": "Нисэх салбар БУМАН төв",
  "address": "ХУД 21-р хороо Буянт Ухаа Спорт цогцолборын баруун талд",
  "region": "Ulaanbaatar",
  "zipcode": "17042",
  "type": "NORMAL",
  "totalCapacity": 15000,
  "contactInfo": {
    "phone": "96268444",
    "email": "warehouse@company.mn"
  },
  "operatingHours": {
    "weekdays": "08:00-18:00",
    "weekends": "09:00-15:00"
  },
  "currency": {
    "kg": 3000,
    "m3": 400,
    "rate": 510
  }
}
### get
GET {{localUrl}}/warehouse/1
Content-Type: application/json


### find-all
GET {{localUrl}}/warehouse?orgId=1&state=ACTIVE&page=1&size=10


### delte
DELETE  {{localUrl}}/warehouse/9
Content-Type: application/json

